### PR TITLE
#255 build a form as inner block in a template

### LINKED ISSUE #255: Marketo Form cannot be embedded in the page template structure
#https://github.com/Netcentric/cn-website/issues/243
When a form need to be embedded into a column then the marketo form does not work.
So if the marketing team need to make it appear on a side of the website, this is not possible currently.

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
Fix #255 

Test URLs:
- Before: https://main--cn-website--netcentric.hlx.page/library/ncwhitepapers-dde
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/library/ncwhitepapers-dde
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/ncwhitepapers-dde
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/drafts/jlledo/ncwhitepapers-dde
- Before: https://main--cn-website--netcentric.hlx.page/drafts/jlledo/two-columns-demo
- After: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/drafts/jlledo/two-columns-demo

### CODE REVIEW

File: templates/two-columns/two-columns.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { loadBlock } from '../../scripts/lib-franklin.js';
+
+export default function buildAutoBlocks() {
+  const columnsBlock = document.querySelector('.columns:has(.form)');
```
Comment (nc-andreashaller) [inline templates/two-columns/two-columns.js:4]: the two column template shouldn't be form specific, it should layout two sections as columns and that's it. The content of the section should be handled by normal block code as they would if no special template would be applied.

**Review by nc-andreashaller — CHANGES_REQUESTED** [review]

File: templates/two-columns/two-columns.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+    if (!hasChildren) {
+      node.remove();
+    }
+  });
+
+  const columnOne = firstSectionIsHero ? [...main.children][1] : [...main.children][0];
+  const columnTwo = firstSectionIsHero ? [...main.children][2] : [...main.children][1];
+  const newSection = document.createElement('section');
+
+  const observer = new MutationObserver((list) => {
```
Comment (nc-andreashaller) [inline templates/two-columns/two-columns.js:44]: do we really need the observer here? what exactly are we waiting for?

File: templates/two-columns/two-columns.js [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+    const isDefault = ratio.includes('50');
+    if (!isDefault) {
+      const [firstRatio, secondRatio] = ratio.split('-');
+      const root = document.querySelector(':root');
+
+      root.style.setProperty('--first-ratio', `${firstRatio}%`);
+      root.style.setProperty('--second-ratio', `${secondRatio}%`);
+
+      columnOne.classList.add('first-column');
+      columnTwo.classList.add('second-column');
```
Comment (nc-andreashaller) [inline templates/two-columns/two-columns.js:20]: these two lines should be outside of the `isDefault` if, otherwise the columns will never get applied, right?

File: templates/two-columns/two-columns.js [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+  [...main.children].forEach((node) => {
+    const hasChildren = [...node.children].length > 0;
+    if (!hasChildren) {
+      node.remove();
+    }
+  });
+
+  const columnOne = firstSectionIsHero ? [...main.children][1] : [...main.children][0];
+  const columnTwo = firstSectionIsHero ? [...main.children][2] : [...main.children][1];
+  const newSection = document.createElement('section');
```
Comment (nc-andreashaller) [inline templates/two-columns/two-columns.js:42]: if I see it correctly the other sections are divs with a class `section`, should we keep the same tags for this one?

File: templates/two-columns/two-columns.js (hunk 2 above)
Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:44]: is needed to wait until the build cycle ends to move the sections. if not, the builder doesn't find them and then doesn't work

File: templates/two-columns/two-columns.js (hunk 4 above)
Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:42]: in fact yes, because they take the correct values from CSS without having to add more code

File: templates/two-columns/two-columns.js (hunk 3 above)
Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:20]: By default, the ratio is 50-50, so these two classes are not needed. unless the ratio is different from 50, then those 2 classes have to be added

File: templates/two-columns/two-columns.js (hunk 2 above)
Comment (nc-andreashaller) [reply templates/two-columns/two-columns.js:44]: which other script is moving the sections?

File: templates/two-columns/two-columns.js (hunk 3 above)
Comment (nc-andreashaller) [reply templates/two-columns/two-columns.js:20]: I tried the fall back and it seems like it is not working: https://255-marketo-form-cannot-be-embedded--cn-website--netcentric.hlx.page/drafts/jlledo/two-columns-demo

File: templates/two-columns/two-columns.js (hunk 2 above)
Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:44]: franklin-lib and scripts are who do the build cycle. this template script has to wait until the build cycle ends. otherwise, the 2 sections don't build properly

Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:44]: the Franklin build cycle is in scripts/lib-franklin.js and scripts/scripts.js. the template is executed before this build cycle, so it has to wait until the cycle ends. the decorateMain function has the main element calls to build the page.
[https://github.com/Netcentric/cn-website/blob/c706b982a36f716ecc031eebc78affe08627b136/scripts/scripts.js#L266](url)
in this function, _buildAutoBlocks_ must be before _decoratesSection_, even if it is an async call, because if not the sections don't build properly. for this reason, the two-columns .js has to wait until the next function call ends

File: templates/two-columns/two-columns.js (hunk 3 above)
Comment (jonatan-lledo-netcentric) [reply templates/two-columns/two-columns.js:20]: fixed

File: templates/two-columns/two-columns.js (hunk 2 above)
Comment (nc-andreashaller) [reply templates/two-columns/two-columns.js:44]: I still don't like the waiting, please create a separate ticket so we can have a look into getting rid of it.

**Review by nc-andreashaller — APPROVED** [review]
